# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

knowledge panels:
    - '(kp|knowledge panels|knowledge panel)'
    
folksonomy engine:
    - '(folksonomy engine)'
    
health card:
    - '(health card)'
    
summary card:
    - '(summary card)'

layout:
    - '(layout)'
    
database:
    - '(database)'
    
mlkit:
    - '(mlkit)'

android:
    - '(android)'
    
ios:
    - '(iphone|ipad|ios)'
    
scan:
    - '(scan)'
    
tests:
    - '(test)'
    
sentry:
    - '(sentry)'

matomo:
    - '(matomo)'

fastlane:
    - '(fastlane)'

darkmode:
    - '(darkmode|Dark mode)'

refactoring:
    - '(Refactoring)'
    
open beauty facts:
    - '(open beauty facts)'
    
###

contribution:
    - '(contribution)'

road to scores:
    - '(road to scores)'

knowledge panels:
    - '(knowledge panels)'

product page:
    - '(product page)'
 
scanning:
    - '(scanning)'
 
settings:
    - '(settings)'
 
scan:
    - '(scan)'
 
help wanted:
    - '(help wanted)'
 
low priority:
    - '(low priority)'
 
high priority:
    - '(high priority)'
 
local cache:
    - '(local cache)'

onboarding:
    - '(onboarding)'

personal search:
    - '(personal search)'
 
search:
    - '(search)'
 
tag picker:
    - '(tag picker)'
 
category picker:
    - '(category picker)'
 
image upload:
    - '(image upload)'
 
photo upload:
    - '(photo upload)'
 
editing:
    - '(editing)'
  
robotoff:
    - '(robotoff)'

preferences:
    - '(preferences)'
 
enhancement:
    - '(enhancement)'
 
ui/ux:
    - '(ui/ux)'
 
launch:
    - '(launch)'
 
translations:
    - '(translations)'
 
screenshot-generation:
    - '(screenshot-generation)'
 
personal scoring:
    - '(personal scoring)'
 
performance:
    - '(performance)'
 
ingredients:
    - '(ingredients)'

image carousel:
    - '(image carousel)'
 
history:
    - '(history)'
 
ecoscore:
    - '(ecoscore)'
 
category explorer:
    - '(category explorer)'
 
tests:
    - '(tests)'
 
speed:
    - '(speed)'
 
sentry:
    - '(sentry)'
 
privacy:
    - '(privacy)'
 
permissions:
    - '(permissions)'
 
packaging input:
    - '(packaging input)'

offline:
    - '(offline)'

nutrition facts:
    - '(nutrition facts)'

mockups available:
    - '(mockups available)'

lists:
    - '(lists)'

gamification:
    - '(gamification)'

dev mode:
    - '(dev mode)'

deeplinking:
    - '(deeplinking)'

analytics:
    - '(analytics)'

attributes:
    - '(attributes)'

splashscreen:
    - '(splashscreen)'

svg:
    - '(svg)'

security:
    - '(security)'

ranking:
    - '(ranking)'
