# Add/remove 'critical' label if issue contains the words 'urgent' or 'critical'
critical:
    - '(critical|urgent)'

knowledge panels:
    - '(kp|knowledge panels)'

layout:
    - '(layout)'
    
database:
    - '(database)'
    
mlkit:
    - '(mlkit)'

android:
    - '(android)'
    
ios:
    - '(iphone|ipad|ios)'
    
scan:
    - '(scan)'
    
tests:
    - '(test)'

darkmode:
    - '(darkmode|Dark mode)'

refactoring:
    - '(Refactoring)'
