### What
- description of the PR

### Screenshot
(Insert a screenshot to provide visual record of your changes, if visible)
### Fixes bug(s)
- #1, #2 and #3 (change by appropriate issues)
### Part of 
- https://github.com/openfoodfacts/smooth-app/issues/525
(please be as granular as possible)
