// TODO(monsieurtanuki): move to off-dart
class TmpToOffNutriments {
  /// Nutrient ids supported by [Nutriments].
  ///
  /// To be used when another source of nutrients (e.g. [OrderedNutrient])
  /// has a broader list of nutrients - that we simply could not handle with
  /// [Nutriments].
  static const Set<String> supportedNutrientIds = <String>{
    'salt',
    'fiber',
    'sugars',
    'fat',
    'saturated-fat',
    'proteins',
    'nova-group',
    'energy',
    'energy-kcal',
    'carbohydrates',
    'caffeine',
    'calcium',
    'iron',
    'vitamin-c',
    'magnesium',
    'phosphorus',
    'potassium',
    'sodium',
    'zinc',
    'copper',
    'selenium',
    'vitamin-a',
    'vitamin-e',
    'vitamin-d',
    'vitamin-b1',
    'vitamin-b2',
    'vitamin-pp',
    'vitamin-b6',
    'vitamin-b12',
    'vitamin-b9',
    'vitamin-k',
    'cholesterol',
    'butyric-acid',
    'caproic-acid',
    'caprylic-acid',
    'capric-acid',
    'lauric-acid',
    'myristic-acid',
    'palmitic-acid',
    'stearic-acid',
    'oleic-acid',
    'linoleic-acid',
    'docosahexaenoic-acid',
    'eicosapentaenoic-acid',
    'erucic-acid',
    'monounsaturated',
    'polyunsaturated',
    'alcohol',
    'pantothenic-acid',
    'biotin',
    'chloride',
    'chromium',
    'fluoride',
    'iodine',
    'manganese',
    'molybdenum',
    'omega-3-fat',
    'omega-6-fat',
    'trans-fat',
  };
}
