
name: Setup env

runs:
  using: "composite"
  steps:
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true
        cache-key: flutter3.00 # change this to force refresh cache

    - run: flutter --version

    - name: Get dependencies
      run: ci/pub_upgrade.sh
