const double LOGGED_IN_APP_BAR_EXPANDED_HEIGHT = 310.0;
const double LOGGED_OUT_APP_BAR_EXPANDED_HEIGHT = 268.0;
const double TOOLBAR_HEIGHT = 92.0;
const double PROFILE_PICTURE_SIZE = 68.0;
const double STATISTICS_CARD_HEIGHT = 68.0;
const double SEARCH_BOTTOM_HEIGHT = 86.0;
