name: cider
version: 0.1.0
description: Tools for Dart package maintainers. Automates CHANGLELOG and pubspec.yaml updates.
homepage: https://github.com/f3ath/cider
repository: https://github.com/f3ath/cider/tree/master
issue_tracker: https://github.com/f3ath/cider/issues

dependencies:
  args: ^1.6.0
  change: ^0.1.0
  intl: ^0.16.1
  markdown: ^2.1.5
  marker: ^0.1.0
  maybe_just_nothing: ^0.3.0
  path: ^1.6.0
  pub_semver: ^1.4.4
  version_manipulation: ^0.0.4
  yaml: ^2.2.1
  yaml_edit: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.3
  test_coverage: ^0.4.3

environment:
  sdk: ">=2.8.0 <3.0.0"

executables:
  cider: cider