// Flutter Supported Languages List
// https://api.flutter.dev/flutter/dart-ui/Locale-class.html

List<String> languageNameList = <String>[
  'Afar',
  'Afrikaans',
  'Akan',
  'Amharic',
  'Arabic',
  'Assamese',
  'Azerbaijani',
  'Belarusian',
  'Bulgarian',
  'Bambara',
  'Bengali',
  'Tibetan',
  'Breton',
  'Bosnian',
  'Catalan',
  'Chechen',
  'Corsican',
  'Czech',
  'Chuvash',
  'Welsh',
  'Danish',
  'German',
  'Greek',
  'English',
  'Esperanto',
  'Spanish',
  'Estonian',
  'Basque',
  'Persian',
  'Finnish',
  'Filipino',
  'Faroese',
  'French',
  'Irish',
  'Scots Gaelic',
  'Galician',
  'Gujarati',
  'Hausa',
  'Hebrew',
  'Hindi',
  'Croatian',
  'Haitian Creole',
  'Hungarian',
  'Armenian',
  'Indonesian',
  'Sichuan Yi',
  'Icelandic',
  'Italian',
  'Inuktitut',
  'Japanese',
  'Javanese',
  'Georgian',
  'Kazakh',
  'Khmer',
  'Kannada',
  'Korean',
  'Kurdish',
  'Cornish',
  'Kirghiz',
  'Latin',
  'Luxembourgish',
  'Lao',
  'Lithuanian',
  'Latvian',
  'Malagasy',
  'Maori',
  'Mongolian',
  'Marathi',
  'Malay',
  'Maltese',
  'Burmese',
  'Norwegian Bokmål',
  'Nepali',
  'Dutch',
  'Norwegian Nynorsk',
  'Norwegian',
  'South Ndebele',
  'Occitan',
  'Panjabi',
  'Polish',
  'Portuguese',
  'Quechua',
  'Romansh',
  'Romanian',
  'Russian',
  'Sanskrit',
  'Sardinian',
  'Sindhi',
  'Sangro',
  'Sinhala',
  'Slovak',
  'Slovenian',
  'Shona',
  'Somali',
  'Albanian',
  'Serbian',
  'Swati',
  'Southern Sotho',
  'Swedish',
  'Swahili',
  'Tamil',
  'Telugu',
  'Tajik',
  'Thai',
  'Tigrinya',
  'Tagalog',
  'Setswana',
  'Turkish',
  'Tsonga',
  'Tatar',
  'Twi',
  'Tahitian',
  'Uighur',
  'Ukrainian',
  'Urdu',
  'Uzbek',
  'Venda',
  'Vietnamese',
  'Walloon',
  'Wolof',
  'Xhosa',
  'Yiddish',
  'Yoruba',
  'Chinese',
  'Zulu',
];

Map<String, String> supportedLanguages = <String, String>{
  'aa': 'Afar',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'am': 'አማርኛ',
  'ar': 'عربى',
  'as': 'অসমীয়া',
  'az': 'Azərbaycan',
  'be': 'беларускi',
  'bg': 'български',
  'bm': 'Bamanankan',
  'bn': 'বাংলা',
  'bo': 'Tibetan',
  'br': 'Breton',
  'bs': 'bosanski',
  'ca': 'català',
  'ce': 'Chechen',
  'co': 'Corsu',
  'cs': 'čeština',
  'cv': 'Chuvash',
  'cy': 'Cymraeg',
  'da': 'dansk',
  'de': 'Deutsch',
  'el': 'Ελληνικά',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Español',
  'et': 'eesti keel',
  'eu': 'euskara',
  'fa': 'فارسی',
  'fi': 'Suomalainen',
  'fil': 'Filipino',
  'fo': 'Faroese',
  'fr': 'Français',
  'ga': 'Gaeilge',
  'gd': 'Scottish Gaelic',
  'gl': 'galego',
  'gu': 'ગુજરાતી',
  'ha': 'હૌસા',
  'he': 'עִברִית',
  'hi': 'हिन्दी',
  'hr': 'Hrvatski',
  'ht': 'ayisyen',
  'hu': 'Magyar',
  'hy': 'հայերեն',
  'id': 'bahasa Indonesia',
  'ii': 'Sichuan Yi',
  'is': 'íslenskur',
  'it': 'Italiano',
  'iu': 'Inuktitut',
  'ja': '日本語',
  'jv': 'basa jawa',
  'ka': 'ქართული',
  'kk': 'қазақ',
  'km': 'ខ្មែរ',
  'kn': 'ಕನ್ನಡ',
  'ko': '한국인',
  'ku': 'Kurdî',
  'kw': 'Cornish',
  'ky': 'Кыргызча',
  'la': 'latīnum',
  'lb': 'lëtzebuergesch',
  'lo': 'ພາສາລາວ',
  'lt': 'lietuvių',
  'lv': 'latviski',
  'mg': 'Malagasy',
  'mi': 'മലയാളം',
  'mn': 'Монгол',
  'mr': 'मराठी',
  'ms': 'Melayu',
  'mt': 'Malti',
  'my': 'မြန်မာဘာသာ',
  'nb': 'Norsk bokmål',
  'ne': 'नेपाली',
  'nl': 'Nederlands',
  'nn': 'Norsk nynorsk',
  'no': 'norsk',
  'nr': 'South Ndebele',
  'oc': 'Occitan',
  'pa': 'Panjabi',
  'pl': 'Polski',
  'pt': 'Português',
  'qu': 'Runasimi',
  'rm': 'Romansh',
  'ro': 'Română',
  'ru': 'Русский',
  'sa': 'संस्कृत',
  'sc': 'Sardinian',
  'sd': 'سنڌي',
  'sg': 'Sango',
  'si': 'සිංහල',
  'sk': 'Slovenčina',
  'sl': 'Slovenščina',
  'sn': 'Shona',
  'so': 'Soomaali',
  'sq': 'shqiptare',
  'sr': 'Српски',
  'ss': 'Swati',
  'st': 'Southern Sotho',
  'sv': 'svenska',
  'sw': 'kiswahili',
  'ta': 'தமிழ்',
  'te': 'తెలుగు',
  'tg': 'тоҷикӣ',
  'th': 'ไทย',
  'ti': 'ትግሪኛ',
  'tl': 'Tagalog',
  'tn': 'Setswana',
  'tr': 'Türk',
  'ts': 'Tsonga',
  'tt': 'Татар',
  'tw': 'Twi',
  'ty': 'Tahitian',
  'ug': 'ئۇيغۇر',
  'uk': 'Українська',
  'ur': 'اردو',
  'uz': "o'zbek",
  've': 'Venda',
  'vi': 'Tiếng Việt',
  'wa': 'Walloon',
  'wo': 'Wolof',
  'xh': 'isiXhosa',
  'yi': 'יידיש',
  'yo': 'Yoruba',
  'zh': '中文',
  'zu': 'Zulu',
};

/*
  Args:
    language Name: The language Name.

    * Non of the language supported has name smaller then 3 characters
    If the language length is 2 then it means the language name is language code.

  Returns:
    List of language code and language name in that language
*/

List<String> getLanguageCodeLangName(String languageName) {
  // Incase of language code is provided
  if (languageName.length == 2) {
    if (supportedLanguages.containsKey(languageName)) {
      return <String>[languageName, supportedLanguages[languageName]!];
    } else {
      // Incase of language code is not supported
      return <String>[languageName, languageName];
    }
  }

  final Map<String, List<String>> languagesNameTranslation =
      <String, List<String>>{
    'Afar': <String>['aa', 'Afar'],
    'Afrikaans': <String>['af', 'Afrikaans'],
    'Akan': <String>['ak', 'Akan'],
    'Amharic': <String>['am', 'አማርኛ'],
    'Arabic': <String>['ar', 'عربى'],
    'Assamese': <String>['as', 'অসমীয়া'],
    'Azerbaijani': <String>['az', 'Azərbaycan'],
    'Belarusian': <String>['be', 'беларускi'],
    'Bulgarian': <String>['bg', 'български'],
    'Bambara': <String>['bm', 'Bamanankan'],
    'Bengali': <String>['bn', 'বাংলা'],
    'Tibetan': <String>['bo', 'Tibetan'],
    'Breton': <String>['br', 'Breton'],
    'Bosnian': <String>['bs', 'bosanski'],
    'Catalan': <String>['ca', 'català'],
    'Chechen': <String>['ce', 'Chechen'],
    'Corsican': <String>['co', 'Corsu'],
    'Czech': <String>['cs', 'čeština'],
    'Chuvash': <String>['cv', 'Chuvash'],
    'Welsh': <String>['cy', 'Cymraeg'],
    'Danish': <String>['da', 'dansk'],
    'German': <String>['de', 'Deutsch'],
    'Greek': <String>['el', 'Ελληνικά'],
    'English': <String>['en', 'English'],
    'Esperanto': <String>['eo', 'Esperanto'],
    'Spanish': <String>['es', 'Español'],
    'Estonian': <String>['et', 'eesti keel'],
    'Basque': <String>['eu', 'euskara'],
    'Persian': <String>['fa', 'فارسی'],
    'Finnish': <String>['fi', 'Suomalainen'],
    'Filipino': <String>['fil', 'Filipino'],
    'Faroese': <String>['fo', 'Faroese'],
    'French': <String>['fr', 'Français'],
    'Irish': <String>['ga', 'Gaeilge'],
    'Scots Gaelic': <String>['gd', 'Scottish Gaelic'],
    'Galician': <String>['gl', 'galego'],
    'Gujarati': <String>['gu', 'ગુજરાતી'],
    'Hausa': <String>['ha', 'હૌસા'],
    'Hebrew': <String>['he', 'עִברִית'],
    'Hindi': <String>['hi', 'हिन्दी'],
    'Croatian': <String>['hr', 'Hrvatski'],
    'Haitian Creole': <String>['ht', 'ayisyen'],
    'Hungarian': <String>['hu', 'Magyar'],
    'Armenian': <String>['hy', 'հայերեն'],
    'Indonesian': <String>['id', 'bahasa Indonesia'],
    'Sichuan Yi': <String>['ii', 'Sichuan Yi'],
    'Icelandic': <String>['is', 'íslenskur'],
    'Italian': <String>['it', 'Italiano'],
    'Inuktitut': <String>['iu', 'Inuktitut'],
    'Japanese': <String>['ja', '日本語'],
    'Javanese': <String>['jv', 'basa jawa'],
    'Georgian': <String>['ka', 'ქართული'],
    'Kazakh': <String>['kk', 'қазақ'],
    'Khmer': <String>['km', 'ខ្មែរ'],
    'Kannada': <String>['kn', 'ಕನ್ನಡ'],
    'Korean': <String>['ko', '한국인'],
    'Kurdish': <String>['ku', 'Kurdî'],
    'Cornish': <String>['kw', 'Cornish'],
    'Kirghiz': <String>['ky', 'Кыргызча'],
    'Latin': <String>['la', 'latīnum'],
    'Luxembourgish': <String>['lb', 'lëtzebuergesch'],
    'Lao': <String>['lo', 'ພາສາລາວ'],
    'Lithuanian': <String>['lt', 'lietuvių'],
    'Latvian': <String>['lv', 'latviski'],
    'Malagasy': <String>['mg', 'Malagasy'],
    'Maori': <String>['mi', 'മലയാളം'],
    'Mongolian': <String>['mn', 'Монгол'],
    'Marathi': <String>['mr', 'मराठी'],
    'Malay': <String>['ms', 'Melayu'],
    'Maltese': <String>['mt', 'Malti'],
    'Burmese': <String>['my', 'မြန်မာဘာသာ'],
    'Norwegian Bokmål': <String>['nb', 'Norsk bokmål'],
    'Nepali': <String>['ne', 'नेपाली'],
    'Dutch': <String>['nl', 'Nederlands'],
    'Norwegian Nynorsk': <String>['nn', 'Norsk nynorsk'],
    'Norwegian': <String>['no', 'norsk'],
    'South Ndebele': <String>['nr', 'South Ndebele'],
    'Occitan': <String>['oc', 'Occitan'],
    'Panjabi': <String>['pa', 'Panjabi'],
    'Polish': <String>['pl', 'Polski'],
    'Portuguese': <String>['pt', 'Português'],
    'Quechua': <String>['qu', 'Runasimi'],
    'Romansh': <String>['rm', 'Romansh'],
    'Romanian': <String>['ro', 'Română'],
    'Russian': <String>['ru', 'Русский'],
    'Sanskrit': <String>['sa', 'संस्कृत'],
    'Sardinian': <String>['sc', 'Sardinian'],
    'Sindhi': <String>['sd', 'سنڌي'],
    'Sangro': <String>['sg', 'Sango'],
    'Sinhala': <String>['si', 'සිංහල'],
    'Slovak': <String>['sk', 'Slovenčina'],
    'Slovenian': <String>['sl', 'Slovenščina'],
    'Shona': <String>['sn', 'Shona'],
    'Somali': <String>['so', 'Soomaali'],
    'Albanian': <String>['sq', 'shqiptare'],
    'Serbian': <String>['sr', 'Српски'],
    'Swati': <String>['ss', 'Swati'],
    'Southern Sotho': <String>['st', 'Southern Sotho'],
    'Swedish': <String>['sv', 'svenska'],
    'Swahili': <String>['sw', 'kiswahili'],
    'Tamil': <String>['ta', 'தமிழ்'],
    'Telugu': <String>['te', 'తెలుగు'],
    'Tajik': <String>['tg', 'тоҷикӣ'],
    'Thai': <String>['th', 'ไทย'],
    'Tigrinya': <String>['ti', 'ትግሪኛ'],
    'Tagalog': <String>['tl', 'Tagalog'],
    'Setswana': <String>['tn', 'Setswana'],
    'Turkish': <String>['tr', 'Türk'],
    'Tsonga': <String>['ts', 'Tsonga'],
    'Tatar': <String>['tt', 'Татар'],
    'Twi': <String>['tw', 'Twi'],
    'Tahitian': <String>['ty', 'Tahitian'],
    'Uighur': <String>['ug', 'ئۇيغۇر'],
    'Ukrainian': <String>['uk', 'Українська'],
    'Urdu': <String>['ur', 'اردو'],
    'Uzbek': <String>['uz', "o'zbek"],
    'Venda': <String>['ve', 'Venda'],
    'Vietnamese': <String>['vi', 'Tiếng Việt'],
    'Walloon': <String>['wa', 'Walloon'],
    'Wolof': <String>['wo', 'Wolof'],
    'Xhosa': <String>['xh', 'isiXhosa'],
    'Yiddish': <String>['yi', 'יידיש'],
    'Yoruba': <String>['yo', 'Yoruba'],
    'Chinese': <String>['zh', '中文'],
    'Zulu': <String>['zu', 'Zulu'],
  };

  if (languagesNameTranslation.containsKey(languageName)) {
    return languagesNameTranslation[languageName]!;
  } else {
    // Just to be safe.
    return <String>[languageName, languageName];
  }
}
