# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:android)

platform :android do
  desc "Deploy to closed beta track"
  lane :closed_beta do
    begin
      gradle(task: "clean")
      gradle(
        task: "bundle",
        build_type: 'Release'
      )
      upload_to_play_store(
        track: 'internal',
        aab: '../build/app/outputs/bundle/release/app-release.aab',
        skip_upload_metadata: true,
        skip_upload_images: true,
        skip_upload_screenshots: true,
        skip_upload_changelogs: true,
        #release_status: "draft",
        version_code: flutter_version(pubspec_location: '../pubspec.yaml')["version_code"],
      )
    end
  end
  lane :setVersion do
      begin
          old_version_code = google_play_track_version_codes(
              package_name: "org.openfoodfacts.app",
              track: "internal",
              json_key: "./fastlane/envfiles/api-4712693179220384697-162836-33ea08672303.json",
          )
          puts "old_version_code: " + old_version_code.to_s
          new_version_code = old_version_code.last().to_i + 1
          puts "new_version_code: " + new_version_code.to_s

          new_version_name = ENV["VERSION_NAME"]
          new_version_name = new_version_name.to_s
          new_version_name = new_version_name[8..-1]
          puts new_version_name

          flutter_set_version(
            path_to_yaml: "../pubspec.yaml",
            version_name: new_version_name,
            version_code: new_version_code.to_s,
          )
      end
  end

end





