name: example
description: Example code for the smooth_ui_library.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  nested: ^1.0.0
  provider: ^6.0.0
  smooth_ui_library:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
