name: Flutter CI


on: pull_request
    
# on: push    # Default will running for every branch.

    
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/smooth_app
    steps:
    
      # Setup Java
      - uses: actions/checkout@v1

      - name: Setup Java 
        uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable' 
      
      - run: flutter pub get
      
      # Check for formatting issues
      # - run: flutter format --set-exit-if-changed .
      
      - name: Analyze
        run: flutter analyze
      
      - name: Build debug APK
        run: flutter build apk --debug
      
      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: packages/smooth_app/build/app/outputs/flutter-apk/app-debug.apk